### ISSUE TITLE
Cannot start installer with Exception in thread "main" java.lang.reflect.InvocationTargetException 

### ISSUE THREAD

**Issue by yoasif** [hdijkema/pcutmp3-gui#1]
I cannot start the installer on my Ubuntu machine.

java -version
java version "1.7.0_25"
OpenJDK Runtime Environment (IcedTea 2.3.12) (7u25-2.3.12-4ubuntu3)
OpenJDK 64-Bit Server VM (build 23.7-b01, mixed mode)

Starting the applet from the command line:

asif@asif-laptop:~/bin/pcutmp3-gui/install$ java -jar pcutmp3gui.jar 

Errors appear:

Exception in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Invalid URL for class: jar:rsrc:jfxrt.jar!/com/sun/glass/utils/NativeLibLoader.class
    at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:281)
    at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:124)
    at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:163)
    at com.sun.javafx.application.LauncherImpl.access$000(LauncherImpl.java:47)
    at com.sun.javafx.application.LauncherImpl$1.run(LauncherImpl.java:115)
    at java.lang.Thread.run(Thread.java:724)
Caused by: java.lang.UnsatisfiedLinkError: Invalid URL for class: jar:rsrc:jfxrt.jar!/com/sun/glass/utils/NativeLibLoader.class
    at com.sun.glass.utils.NativeLibLoader.loadLibraryFullPath(NativeLibLoader.java:145)
    at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:88)
    at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:31)
    at com.sun.glass.ui.Application.loadNativeLibrary(Application.java:73)
    at com.sun.glass.ui.Application.loadNativeLibrary(Application.java:80)
    at com.sun.glass.ui.gtk.GtkPlatformFactory$1.run(GtkPlatformFactory.java:28)
    at com.sun.glass.ui.gtk.GtkPlatformFactory$1.run(GtkPlatformFactory.java:25)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.glass.ui.gtk.GtkPlatformFactory.<clinit>(GtkPlatformFactory.java:25)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:190)
    at com.sun.glass.ui.PlatformFactory.getPlatformFactory(PlatformFactory.java:20)
    at com.sun.glass.ui.Application.Run(Application.java:103)
    at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:271)
    ... 5 more

Any help fixing this is highly appreciated!

**Comment by hdijkema** [comment]
I fixed this issue in a new setup and it can be downloaded from https://github.com/hoesterholt/pcutmp3-gui/blob/master/Output/PCutMp3GUI_Setup.exe?raw=true
